export const PROFESSIONS = [
  'سباك',
  'كهربائي',
  'نجار',
  'نقاش',
  'فني تكييف',
  'أجهزة منزلية',
  'حداد',
  'ألوميتال وزجاج',
  'دش وستالايت',
  'كاميرات وشبكات',
  'سيراميك وأرضيات',
  'جبس بورد وديكور',
  'عزل وأسطح',
  'تنظيف وصيانة',
  'ميكانيكي',
  'سمكري',
];

export const SERVICE_ICONS_MAP = {
  سباك: 'FaWrench',
  كهربائي: 'FaBolt',
  نجار: 'FaHammer',
  نقاش: 'FaPaintRoller',
  'فني تكييف': 'FaSnowflake',
  'أجهزة منزلية': 'FaTv',
  حداد: 'FaFireAlt',
  'ألوميتال وزجاج': 'FaDoorOpen',
  'دش وستالايت': 'FaSatelliteDish',
  'كاميرات وشبكات': 'FaVideo',
  'سيراميك وأرضيات': 'FaThLarge',
  'جبس بورد وديكور': 'FaBrush',
  'عزل وأسطح': 'FaShieldAlt',
  'تنظيف وصيانة': 'FaBroom',
  ميكانيكي: 'FaTools',
  سمكري: 'FaWrench',
};
